### ISSUE TITLE
Django 1.8 not supported

### ISSUE THREAD

**Issue by tbazadaykin** [maxirobaina/django-firebird#37]
Here what i have

    Django==1.8
    django-firebird===1.6.1.final.0
    fdb==1.4.4

Query causes an error:

    'firebird' isn't an available database backend.
    Try using 'django.db.backends.XXX', where XXX is one of:
        u'base', u'mysql', u'oracle', u'postgresql_psycopg2', u'sqlite3'
    Error was: cannot import name BaseDatabaseOperations

**Comment by mariuz** [comment]
Hello you can test the develop branch for 1.7.x support and send us feedback or pull requests

http://www.firebirdnews.org/firebird-django-1-7-support-experimental/

**Comment by AdamDavin** [comment]
Good Afternoon, 

I have started trying to get Python(3.43x86) Django(1.8), Mezzanine(4.01), Cartridge(0.10.0) and fdb(1.4.10) Firebird (2.54) to play nice. I have checked out django-firebird 1.6.4 from GIT and run "python setup.py install" to install it into the virtual environment. 
I am currently running in a Windows 7 Environment. 
Initial changes to files to cover not found errors. Lines beginning with # were original lines in those files that I commented out and then replaced. (Sorry I am still catching up on the use of GIT)

operations.py 
#from django.db.backends import BaseDatabaseOperations, util
from django.db.backends import utils
from django.db.backends.base.operations import BaseDatabaseOperations

client.py
#from django.db.backends import BaseDatabaseClient
from django.db.backends.base.client import BaseDatabaseClient

creation.py
#from django.db.backends.creation import BaseDatabaseCreation
from django.db.backends.base.creation import BaseDatabaseCreation

introspection.py
#from django.db.backends import BaseDatabaseIntrospection
from django.db.backends.base.introspection import BaseDatabaseIntrospection

base.py
from django.db.backends.base.features import *
from django.db.backends.base.validation import *
from django.db.backends.base.base import *

Now I am currently getting the error below which is a bit vague. 

(mezzcartfb) e:\work\git\venv\mezzcartfb\mezzcartfb>python manage.py createdb
e:\work\git\venv\mezzcartfb\lib\site-packages\mezzanine\utils\conf.py:51: UserWarning: You haven't defined the ALLOWED_HOSTS settings, which Django requires. Will fall back to the domains configured as sites.
  warn("You haven't defined the ALLOWED_HOSTS settings, which "
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "e:\work\git\venv\mezzcartfb\lib\site-packages\django\core\management\__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "e:\work\git\venv\mezzcartfb\lib\site-packages\django\core\management\__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "e:\work\git\venv\mezzcartfb\lib\site-packages\django\core\management\base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "e:\work\git\venv\mezzcartfb\lib\site-packages\django\core\management\base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "e:\work\git\venv\mezzcartfb\lib\site-packages\mezzanine\core\management\commands\createdb.py", line 51, in handle
    if "conf_setting" in connection.introspection.table_names():
  File "e:\work\git\venv\mezzcartfb\lib\site-packages\django\db\backends\base\introspection.py", line 57, in table_names
    return get_names(cursor)
  File "e:\work\git\venv\mezzcartfb\lib\site-packages\django\db\backends\base\introspection.py", line 53, in get_names
    return sorted(ti.name for ti in self.get_table_list(cursor)
  File "e:\work\git\venv\mezzcartfb\lib\site-packages\django\db\backends\base\introspection.py", line 54, in <genexpr>
    if include_views or ti.type == 't')
AttributeError: 'str' object has no attribute 'type'

(mezzcartfb) e:\work\git\venv\mezzcartfb\mezzcartfb>

I have not yet tried the development branch as that seems to be further behind that 1.6.4 is this correct? 

Any Thoughts? 

Best Regards, 

Adam Davin.

**Comment by cfingerh** [comment]
Hi Adam, 

i did some changes to the code to work with 1.8. It is not tested and migration has to be disabled ( in the django code runserver.py disable check_migrations)

the code is forked in https://github.com/cfingerh/django-firebird

**Comment by mariuz** [comment]
i have created a pull request for devel from your fork 
https://github.com/maxirobaina/django-firebird/pull/45

@maxirobaina  could you review and comment ?

**Comment by maxirobaina** [comment]
Hi everyone,

Yes!! I'll have a look. Thanks for contribute.
I've been a little busy lately. My idea is release a django-firebird for django 1.7 first and then work quickly into a django 1.8 support, mainly because It's a LTS version.

I hope this weekend, release a beta django-firebird 1.7

Regards.

**Comment by raphaelm** [comment]
Will this still happen? :)

**Comment by geovanisouza92** [comment]
I'm facing the same problem, Django==1.9

**Comment by CountZachula** [comment]
Any updates on 1.8 or 1.9 support?

**Comment by maxirobaina** [comment]
The master branch contains now an alpha version with django 1.8.x supports
I'll appreciate any feedback.
